<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login' => 'Entrar',
    'no' => 'No',
    'yes' => 'Yes',
    'About' => 'This is about QuieroCasa.',
    'Detail' => 'Detail',
    'Home' => 'Home',
    'Logout' => 'Logout',
    'Search' => 'Search',
    'Sign in' => 'Sign in',
    'Sign up' => 'Sign up',
    'Signup' => 'Sign up',
    'Starred' => 'Starred',
    'Welcome description' => 'A web site where you might find real states ',
    'Welcome to QuieroCasa' => 'Welcome to QuieroCasa.com.uy',
    'forgotpss' => 'If you forgot your password you can ',
    'login instructions' => 'Please fill out the following fields to login:',
    'see detail' => 'To se the detail <a href="{0}">click here</a>',
    'signup instructions' => 'Please fill out the following fields to signup:',
];
