<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Detail' => 'Detalle',
    'Home' => 'Inicio',
    'Logout' => 'Salir',
    'Search' => 'Buscar',
    'Sign in' => 'Entrar',
    'Sign up' => 'Unirse',
    'Signup' => 'Unirse',
    'Starred' => 'Favoritos',
    'forgotpss' => 'Si olvidaste tu contrasena has click aqui:',
    'you know' => '@@tu sabes@@',
    'About' => 'Esta pagin es sobre Quiero casa.',
    'Welcome description' => 'Un portal donde usted va a poder encontrar las propiedades que anda buscando',
    'Welcome to QuieroCasa' => 'Bienvenido a QuieroCasa.com.uy',
    'login instructions' => 'Por favor complete el formulario con los sigiente campos para ingresar',
    'see detail' => 'Para ver el detalle haga <a href="{0}">click aqui</a>',
    'signup instructions' => 'Por favor ingrese los campos requeridos para unirse:',
];
